title: Himangshu Hazarika -> Experiments in code
description: An anthology of my victories and defeats in computer programming

url: https://himangshuj.github.io
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact

social:
   github: himangshuj
   twitter: himangshuj
   facebook: hjhazarika
   email: hjhazarika@gmail.com

google_analytics: "UA-74531944-1"
